GET http://localhost:8080/issues

###

GET http://localhost:8080/issues/600459035ddba329c40c8767

###

POST http://localhost:8080/issues 
Content-Type: application/json

{
  "issueId": "123gagas9977",
  "author": "Gerry Scotty",
  "project": "Mike pence resume",
  "description": "looking for a job",
  "active": true,
  "priority": "high"
}

###

PATCH http://localhost:8080/issues/60045929d2753f2a0a897494
Content-Type: application/json

{
  "active": "false",
  "priority": "low",
  "description": "updated issue"
}