GET http://localhost:8080/users

###

GET http://localhost:8080/users/60058d4de68b52622bcc385b

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "userId": "1123jndand",
  "userName": "Gianni Morandi",
  "userPassword": "password"
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "userName": "Gianni Morandi",
  "userPassword": "pass"
}


###

PATCH http://localhost:8080/projects/600586853f37e75fa1476d14
Content-Type: application/json

{
  "teamMembers": ["jerry scotti"]
}

###
DELETE http://localhost:8080/users/6005b23b5a6e1e63056025d5